watchlist:
  - symbol: "600967"
    name: "内蒙一机"
    sector: "军工"
  - symbol: "601899"
    name: "紫金矿业"
    sector: "有色金属"
  - symbol: "603993"
    name: "洛阳钼业"
    sector: "有色金属"
  - symbol: "000750"
    name: "国海证券"
    sector: "证券"
  - symbol: "002466"
    name: "天齐锂业"
    sector: "有色金属"
